/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    colors: Color;
    'vein-patterns': VeinPattern;
    dimensions: Dimension;
    thicknesses: Thickness;
    finishes: Finish;
    products: Product;
    catalogs: Catalog;
    dealers: Dealer;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    'vein-patterns': VeinPatternsSelect<false> | VeinPatternsSelect<true>;
    dimensions: DimensionsSelect<false> | DimensionsSelect<true>;
    thicknesses: ThicknessesSelect<false> | ThicknessesSelect<true>;
    finishes: FinishesSelect<false> | FinishesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    catalogs: CatalogsSelect<false> | CatalogsSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fa' | 'en' | 'ar') | ('fa' | 'en' | 'ar')[];
  globals: {
    'about-page': AboutPage;
    'home-page': HomePage;
    'care-page': CarePage;
    'applications-page': ApplicationsPage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'care-page': CarePageSelect<false> | CarePageSelect<true>;
    'applications-page': ApplicationsPageSelect<false> | ApplicationsPageSelect<true>;
  };
  locale: 'fa' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * مدیریت حساب کاربری ادمین
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * عنوان/متن جایگزین تصویر برای سئو و موتورهای جستجو (مثال: اسلب پرسیس کوارتز)
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vein-patterns".
 */
export interface VeinPattern {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dimensions".
 */
export interface Dimension {
  id: number;
  /**
   * عنوان ابعاد اسلب (مثلاً: 320 × 75 cm یا 320 × 160 cm Jumbo)
   */
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thicknesses".
 */
export interface Thickness {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes".
 */
export interface Finish {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * نام مدل سنگ (مثلاً: مه البرز / Alborz Mist)
   */
  title: string;
  /**
   * اسلاگ سئو برای URL (مثلاً: alborz-mist)
   */
  slug: string;
  /**
   * کد اختصاصی سنگ (مثلاً: PQ-202)
   */
  code: string;
  /**
   * سری/دسته‌بندی سنگ (تک‌رنگ، رگه‌دار، کالاکاتا)
   */
  category: number | Category;
  /**
   * طیف رنگی اصلی سنگ
   */
  color_family: number | Color;
  /**
   * الگوی رگه (مثلاً رگه نازک، رگه ضخیم، ابر و بادی)
   */
  vein_pattern?: (number | null) | VeinPattern;
  /**
   * وضعیت تولید اسلب در کارخانه
   */
  is_in_stock?: ('active' | 'discontinued') | null;
  /**
   * نمایش این محصول در بخش محصولات منتخب (صفحه اصلی)
   */
  is_featured?: boolean | null;
  /**
   * تصویر اصلی و تمام‌قد اسلب (Full Slab Scan)
   */
  thumbnail?: (number | null) | Media;
  /**
   * گالری اسلایدر تصاویر (بافت نزدیک و اجرا در محیط)
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * توضیح تصویر (مثلاً: اجرا در کانتر آشپزخانه)
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * انتخاب ضخامت‌های استاندارد خط تولید برای این اسلب از کالکشن ضخامت‌ها
   */
  thicknesses?: (number | Thickness)[] | null;
  /**
   * امکان سفارش تولید با ضخامت خاص سفارشی (پیش‌فرض فعال)
   */
  custom_thickness_available?: boolean | null;
  /**
   * انتخاب پرداخت‌های سطحی قابل عرضه از بخش Attributes > Finishes
   */
  finishes?: (number | Finish)[] | null;
  /**
   * ابعاد قابل عرضه اسلب (امکان انتخاب ابعاد جدید در آینده)
   */
  dimensions?: (number | Dimension)[] | null;
  /**
   * توضیحات معمارانه و سئومحور سنگ
   */
  description?: string | null;
  /**
   * عنوان متای سئو گوگل
   */
  meta_title?: string | null;
  /**
   * توضیحات متای سئو گوگل
   */
  meta_description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs".
 */
export interface Catalog {
  id: number;
  /**
   * عنوان کاتالوگ (مثلاً: کاتالوگ جامع اسلب‌ها / مشخصات فنی و دیتیل)
   */
  title: string;
  slug: string;
  /**
   * سال انتشار (مانند 2026 یا 2025)
   */
  year: number;
  catalog_type: 'full_catalog' | 'technical' | 'collection' | 'guide';
  description?: string | null;
  cover_image: number | Media;
  pdf_file: number | Media;
  /**
   * حجم فایل (MB)
   */
  file_size_mb: number;
  /**
   * تعداد صفحات (اختیاری)
   */
  page_count?: number | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  title: string;
  province:
    | 'alborz'
    | 'ardabil'
    | 'azerbaijan-east'
    | 'azerbaijan-west'
    | 'bushehr'
    | 'chaharmahal-and-bakhtiari'
    | 'fars'
    | 'gilan'
    | 'golestan'
    | 'hamadan'
    | 'hormozgan'
    | 'ilam'
    | 'isfahan'
    | 'kerman'
    | 'kermanshah'
    | 'khorasan-north'
    | 'khorasan-razavi'
    | 'khorasan-south'
    | 'khuzestan'
    | 'kohgiluyeh-and-boyer-ahmad'
    | 'kurdistan'
    | 'lorestan'
    | 'markazi'
    | 'mazandaran'
    | 'qazvin'
    | 'qom'
    | 'semnan'
    | 'sistan-and-baluchestan'
    | 'tehran'
    | 'yazd'
    | 'zanjan';
  city: string;
  address: string;
  phone: string;
  order?: number | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'general' | 'sample' | 'project' | 'dealer';
  status: 'new' | 'in_progress' | 'resolved' | 'archived';
  fullName: string;
  email?: string | null;
  phone: string;
  country: string;
  company?: string | null;
  city?: string | null;
  postalCode?: string | null;
  address?: string | null;
  productCodes?: string | null;
  projectSize?: string | null;
  thickness?: string | null;
  finish?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'vein-patterns';
        value: number | VeinPattern;
      } | null)
    | ({
        relationTo: 'dimensions';
        value: number | Dimension;
      } | null)
    | ({
        relationTo: 'thicknesses';
        value: number | Thickness;
      } | null)
    | ({
        relationTo: 'finishes';
        value: number | Finish;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'catalogs';
        value: number | Catalog;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vein-patterns_select".
 */
export interface VeinPatternsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dimensions_select".
 */
export interface DimensionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thicknesses_select".
 */
export interface ThicknessesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes_select".
 */
export interface FinishesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  code?: T;
  category?: T;
  color_family?: T;
  vein_pattern?: T;
  is_in_stock?: T;
  is_featured?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  thicknesses?: T;
  custom_thickness_available?: T;
  finishes?: T;
  dimensions?: T;
  description?: T;
  meta_title?: T;
  meta_description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs_select".
 */
export interface CatalogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  catalog_type?: T;
  description?: T;
  cover_image?: T;
  pdf_file?: T;
  file_size_mb?: T;
  page_count?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  title?: T;
  province?: T;
  city?: T;
  address?: T;
  phone?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  country?: T;
  company?: T;
  city?: T;
  postalCode?: T;
  address?: T;
  productCodes?: T;
  projectSize?: T;
  thickness?: T;
  finish?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * مدیریت جامع رسانه‌ها، بیانیه‌ها و محتوای صفحه درباره پرسیس
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  visionTag?: string | null;
  visionTitle?: string | null;
  visionDesc1?: string | null;
  visionDesc2?: string | null;
  /**
   * پیشنهاد: نمای خط تولید پیشرفته یا بافت کلوزآپ اسلب
   */
  visionImage?: (number | null) | Media;
  galleryTag?: string | null;
  galleryTitle?: string | null;
  /**
   * تصاویر مورد نظر را از گالری مدیاهای موجود انتخاب یا آپلود کنید. ترتیب نمایش با درگ اند دراپ قابل تغییر است.
   */
  galleryImages?: (number | Media)[] | null;
  craftsmanshipTag?: string | null;
  craftsmanshipTitle?: string | null;
  craftsmanshipDesc?: string | null;
  /**
   * پیشنهاد: اجرای سنگ در کانتر لوکس آشپزخانه یا فضاهای مدرن
   */
  craftsmanshipImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * مدیریت یکپارچه هیرو بنر، رسانه‌ها و بخش‌های صفحه نخست
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * متن کوچک بالای تیتر (مثال: PERSIS QUARTZ)
   */
  tagline?: string | null;
  /**
   * تیتر بزرگ و معمارانه هیرو بنر
   */
  title?: string | null;
  /**
   * توضیح کوتاه ۱ تا ۲ خطی زیر تیتر اصلی
   */
  subtitle?: string | null;
  /**
   * تصویر افقی دسکتاپ با نسبت 16:9 (پیشنهادی: 1920x1080)
   */
  desktopPoster?: (number | null) | Media;
  /**
   * ویدیوی بدون صدا و بهینه‌شده برای دسکتاپ (اختیاری)
   */
  desktopVideo?: (number | null) | Media;
  /**
   * تصویر عمودی موبایل با نسبت 9:16 (پیشنهادی: 1080x1920)
   */
  mobilePoster?: (number | null) | Media;
  /**
   * ویدیوی عمودی موبایل جهت بهینه‌سازی بارگذاری (اختیاری)
   */
  mobileVideo?: (number | null) | Media;
  infoCardsImages?: {
    /**
     * پیشنهاد: کلوزآپ بافت کوارتز یا تست‌های آزمایشگاهی
     */
    featuresImage?: (number | null) | Media;
    /**
     * پیشنهاد: فضای آشپزخانه تمیز و کانترتاپ لوکس
     */
    maintenanceImage?: (number | null) | Media;
    /**
     * پیشنهاد: ژورنال معماری یا کاتالوگ بازشده
     */
    catalogsImage?: (number | null) | Media;
    /**
     * پیشنهاد: پالت یا جعبه نمونه‌سنگ‌های لوکس
     */
    sampleImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * مدیریت تصویر، مراحل آکاردئون و هشدارهای مراقبتی
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care-page".
 */
export interface CarePage {
  id: number;
  media?: (number | null) | Media;
  steps?:
    | {
        stepNumber?: string | null;
        iconName?:
          | (
              | 'dot'
              | 'droplets'
              | 'checkCheck'
              | 'shieldCheck'
              | 'sparkles'
              | 'spray'
              | 'brush'
              | 'flame'
              | 'heat'
              | 'cookingPot'
              | 'utensils'
              | 'chefHat'
              | 'scratch'
              | 'chemical'
              | 'impact'
              | 'hammer'
              | 'ban'
              | 'balloon'
              | 'bicep'
              | 'bot'
              | 'crown'
              | 'castle'
              | 'drama'
              | 'ghost'
              | 'frown'
              | 'meh'
              | 'laugh'
              | 'smile'
              | 'annoyed'
              | 'smilePlus'
              | 'hand'
              | 'handHelping'
              | 'heart'
              | 'heartCrack'
              | 'heartPulse'
              | 'leaf'
              | 'partyPopper'
              | 'ribbon'
              | 'salad'
              | 'star'
              | 'starHalf'
              | 'starOff'
              | 'thumbsDown'
              | 'thumbsUp'
              | 'waves'
            )
          | null;
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  rules?:
    | {
        title: string;
        iconType?:
          | (
              | 'dot'
              | 'droplets'
              | 'checkCheck'
              | 'shieldCheck'
              | 'sparkles'
              | 'spray'
              | 'brush'
              | 'flame'
              | 'heat'
              | 'cookingPot'
              | 'utensils'
              | 'chefHat'
              | 'scratch'
              | 'chemical'
              | 'impact'
              | 'hammer'
              | 'ban'
              | 'balloon'
              | 'bicep'
              | 'bot'
              | 'crown'
              | 'castle'
              | 'drama'
              | 'ghost'
              | 'frown'
              | 'meh'
              | 'laugh'
              | 'smile'
              | 'annoyed'
              | 'smilePlus'
              | 'hand'
              | 'handHelping'
              | 'heart'
              | 'heartCrack'
              | 'heartPulse'
              | 'leaf'
              | 'partyPopper'
              | 'ribbon'
              | 'salad'
              | 'star'
              | 'starHalf'
              | 'starOff'
              | 'thumbsDown'
              | 'thumbsUp'
              | 'waves'
            )
          | null;
        desc: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * مدیریت شوکیس، مانیفست و بخش‌های کاربردی معماری
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications-page".
 */
export interface ApplicationsPage {
  id: number;
  headerTag?: string | null;
  headerTitle: string;
  headerDesc: string;
  showcaseItems?:
    | {
        tag: string;
        desktopImage?: (number | null) | Media;
        mobileImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        num: string;
        enTag: string;
        title: string;
        desc: string;
        specs?:
          | {
              label: string;
              val?: string | null;
              id?: string | null;
            }[]
          | null;
        gallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  visionTag?: T;
  visionTitle?: T;
  visionDesc1?: T;
  visionDesc2?: T;
  visionImage?: T;
  galleryTag?: T;
  galleryTitle?: T;
  galleryImages?: T;
  craftsmanshipTag?: T;
  craftsmanshipTitle?: T;
  craftsmanshipDesc?: T;
  craftsmanshipImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  desktopPoster?: T;
  desktopVideo?: T;
  mobilePoster?: T;
  mobileVideo?: T;
  infoCardsImages?:
    | T
    | {
        featuresImage?: T;
        maintenanceImage?: T;
        catalogsImage?: T;
        sampleImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care-page_select".
 */
export interface CarePageSelect<T extends boolean = true> {
  media?: T;
  steps?:
    | T
    | {
        stepNumber?: T;
        iconName?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  rules?:
    | T
    | {
        title?: T;
        iconType?: T;
        desc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications-page_select".
 */
export interface ApplicationsPageSelect<T extends boolean = true> {
  headerTag?: T;
  headerTitle?: T;
  headerDesc?: T;
  showcaseItems?:
    | T
    | {
        tag?: T;
        desktopImage?: T;
        mobileImage?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        num?: T;
        enTag?: T;
        title?: T;
        desc?: T;
        specs?:
          | T
          | {
              label?: T;
              val?: T;
              id?: T;
            };
        gallery?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}